import vendor.hvac.HVAC;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mconklin' at '4/13/15 3:29 PM' with Gradle 2.2
 *
 * @author mconklin, @date 4/13/15 3:29 PM
 */
public class EnvironmentControllerImpl implements EnvironmentController {

    private static final int MIN_TEMP = 65, MAX_TEMP = 75;

    private boolean fanOn;
    private boolean heaterOn;
    private boolean coolerOn;

    private HVAC hvac;

    public EnvironmentControllerImpl(HVAC hvac) {
        this.hvac = hvac;
    }

    @Override
    public void tick() {
        int currentTemp = hvac.temp();
        if (currentTemp < MIN_TEMP) {
            switchHeat(true);
            switchFan(true);
        } else if (currentTemp > MAX_TEMP) {
            switchCooler(true);
            switchFan(true);
        }
    }

    private void switchHeat(boolean state) {
        hvac.heat(state);
        heaterOn = state;
    }

    private void switchCooler(boolean state) {
        hvac.cool(state);
        coolerOn = state;
    }

    private void switchFan(boolean state) {
        hvac.fan(state);
        fanOn = state;
    }

    public boolean isFanOn() {
        return fanOn;
    }

    public boolean isHeaterOn() {
        return heaterOn;
    }

    public boolean isCoolerOn() {
        return coolerOn;
    }

    public boolean dormant() {
        return !fanOn && !heaterOn && !coolerOn;
    }
}
