import vendor.hvac.HVAC;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mconklin' at '4/13/15 3:29 PM' with Gradle 2.2
 *
 * @author mconklin, @date 4/13/15 3:29 PM
 */
public class EnvironmentControllerImpl implements EnvironmentController {

    @Override
    public void tick() {

    }

    private boolean fanOn;
    private boolean heaterOn;
    private boolean coolerOn;

    private HVAC hvac;

    public EnvironmentControllerImpl(HVAC hvac) {
        this.hvac = hvac;
    }


    public boolean isFanOn() {
        return fanOn;
    }

    public boolean isHeaterOn() {
        return heaterOn;
    }

    public boolean isCoolerOn() {
        return coolerOn;
    }

    public boolean dormant() {
        return !fanOn && !heaterOn && !coolerOn;
    }
}
