import org.junit.Test;
import vendor.hvac.FakeHVAC;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mconklin' at '4/13/15 3:29 PM' with Gradle 2.2
 *
 * @author mconklin, @date 4/13/15 3:29 PM
 */
public class EnvironmentControllerImplTest {

    @Test
    public void ShouldDoNothingIfTemperatureIsOK() {
        EnvironmentControllerImpl controller = new EnvironmentControllerImpl(new FakeHVAC());

        assertTrue(controller.dormant());
    }
}
