import org.junit.Test;
import vendor.hvac.FakeHVAC;
import vendor.hvac.HVAC;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mconklin' at '4/13/15 3:29 PM' with Gradle 2.2
 *
 * @author mconklin, @date 4/13/15 3:29 PM
 */
public class EnvironmentControllerImplTest {

    @Test
    public void ShouldDoNothingIfTemperatureIsOK() {
        EnvironmentControllerImpl controller = new EnvironmentControllerImpl(new FakeHVAC());

        assertTrue(controller.dormant());
    }

    @Test
    public void TurnHeatOnIfTemperatureIsBelow65() {
        FakeHVAC testHVAC = new FakeHVAC(63);
        EnvironmentControllerImpl controller = new EnvironmentControllerImpl(testHVAC);
        controller.tick();
        assertTrue(testHVAC.heatCount == 1);
        assertTrue(testHVAC.coolCount == 0);
        assertTrue(testHVAC.fanCount == 1);
        assertTrue(controller.isHeaterOn());
        assertTrue(controller.isFanOn());
    }

    @Test
    public void TurnCoolerOnIfTemperatureIsAbove75() {
        FakeHVAC testHVAC = new FakeHVAC(77);
        EnvironmentControllerImpl controller = new EnvironmentControllerImpl(testHVAC);
        controller.tick();
        assertTrue(testHVAC.heatCount == 0);
        assertTrue(testHVAC.coolCount == 1);
        assertTrue(testHVAC.fanCount == 1);
        assertTrue(controller.isCoolerOn());
        assertTrue(controller.isFanOn());
    }
}
